---
name: test-deployment
update:
  canaries: 1
  canary_watch_time: 30000-1200000
  max_in_flight: ((max_in_flight))
  serial: false
  update_watch_time: 5000-1200000
  really: ((cool))
  var_file_interpolation: ((interesting_var))
instance_groups:
- name: dummy
  azs: [z1]
  instances: 1
  vm_type: minimal
  stemcell: default
  networks: [name: default]
  jobs:
  - name: dummy
    release: dummy

releases:
- name: dummy
  version: latest

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

variables:
- name: cool
  type: password
- name: super_sekret
  type: password
